"""Add remaining 8 modules (finances, comms, events, elections, docs, analytics, workflows)

Revision ID: 0040638c77bf
Revises: ac8b8a4a13f3
Create Date: 2026-07-22 14:10:56.116882
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0040638c77bf'
down_revision: Union[str, None] = 'ac8b8a4a13f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_insights',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('insight_type', sa.String(length=50), nullable=False),
    sa.Column('source_data', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_insights_tenant_id'), 'ai_insights', ['tenant_id'], unique=False)
    op.create_table('announcements',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('audience', sa.String(length=50), nullable=False),
    sa.Column('target_group_ids', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'PUBLISHED', 'ARCHIVED', name='announcementstatus'), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('allow_comments', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_tenant_id'), 'announcements', ['tenant_id'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('OPERATIONS', 'EVENTS', 'MARKETING', 'TRAVEL', 'TECHNOLOGY', 'PROFESSIONAL_SERVICES', 'FACILITIES', 'INSURANCE', 'OTHER', name='expensecategory'), nullable=False),
    sa.Column('period', sa.Enum('MONTHLY', 'QUARTERLY', 'ANNUAL', name='budgetperiod'), nullable=False),
    sa.Column('planned_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('alert_threshold', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_tenant_id'), 'budgets', ['tenant_id'], unique=False)
    op.create_table('dashboards',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('layout', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboards_tenant_id'), 'dashboards', ['tenant_id'], unique=False)
    op.create_table('data_exports',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('export_type', sa.String(length=50), nullable=False),
    sa.Column('format', sa.Enum('JSON', 'CSV', 'PDF', 'EXCEL', name='reportformat'), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_exports_tenant_id'), 'data_exports', ['tenant_id'], unique=False)
    op.create_table('document_categories',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('parent_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['document_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_categories_tenant_id'), 'document_categories', ['tenant_id'], unique=False)
    op.create_table('dues_structures',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('prorate', sa.Boolean(), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dues_structures_tenant_id'), 'dues_structures', ['tenant_id'], unique=False)
    op.create_table('elections',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('election_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'NOMINATIONS_OPEN', 'VOTING', 'CLOSED', 'RESULTS_PUBLISHED', name='electionstatus'), nullable=False),
    sa.Column('nominations_open', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nominations_close', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voting_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voting_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seats_available', sa.Integer(), nullable=False),
    sa.Column('max_candidates_per_seat', sa.Integer(), nullable=True),
    sa.Column('min_votes_required', sa.Integer(), nullable=True),
    sa.Column('quorum_percentage', sa.Integer(), nullable=False),
    sa.Column('require_unanimous', sa.Boolean(), nullable=False),
    sa.Column('vote_method', sa.Enum('ONLINE', 'MAIL', 'IN_PERSON', name='votemethod'), nullable=False),
    sa.Column('allow_abstain', sa.Boolean(), nullable=False),
    sa.Column('secret_ballot', sa.Boolean(), nullable=False),
    sa.Column('multiple_rounds', sa.Boolean(), nullable=False),
    sa.Column('ranked_choice', sa.Boolean(), nullable=False),
    sa.Column('total_eligible_voters', sa.Integer(), nullable=False),
    sa.Column('total_votes_cast', sa.Integer(), nullable=False),
    sa.Column('quorum_met', sa.Boolean(), nullable=False),
    sa.Column('results_summary', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elections_tenant_id'), 'elections', ['tenant_id'], unique=False)
    op.create_table('email_campaigns',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('preview_text', sa.String(length=200), nullable=True),
    sa.Column('html_body', sa.Text(), nullable=False),
    sa.Column('plain_body', sa.Text(), nullable=True),
    sa.Column('target_segments', sa.JSON(), nullable=True),
    sa.Column('target_group_ids', sa.JSON(), nullable=True),
    sa.Column('target_all', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'SENDING', 'SENT', 'PAUSED', 'CANCELLED', name='campaignstatus'), nullable=False),
    sa.Column('total_recipients', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('delivered_count', sa.Integer(), nullable=False),
    sa.Column('opened_count', sa.Integer(), nullable=False),
    sa.Column('clicked_count', sa.Integer(), nullable=False),
    sa.Column('bounced_count', sa.Integer(), nullable=False),
    sa.Column('unsubscribed_count', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('from_name', sa.String(length=100), nullable=False),
    sa.Column('from_email', sa.String(length=200), nullable=False),
    sa.Column('reply_to', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_campaigns_tenant_id'), 'email_campaigns', ['tenant_id'], unique=False)
    op.create_table('email_templates',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('html_body', sa.Text(), nullable=False),
    sa.Column('plain_body', sa.Text(), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_templates_tenant_id'), 'email_templates', ['tenant_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('banner_url', sa.String(length=500), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CANCELLED', 'COMPLETED', name='eventstatus'), nullable=False),
    sa.Column('is_virtual', sa.Boolean(), nullable=False),
    sa.Column('is_hybrid', sa.Boolean(), nullable=False),
    sa.Column('virtual_link', sa.String(length=500), nullable=True),
    sa.Column('virtual_platform', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registration_open', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registration_close', sa.DateTime(timezone=True), nullable=True),
    sa.Column('venue_name', sa.String(length=200), nullable=True),
    sa.Column('venue_address', sa.Text(), nullable=True),
    sa.Column('venue_city', sa.String(length=100), nullable=True),
    sa.Column('venue_country', sa.String(length=100), nullable=True),
    sa.Column('venue_lat', sa.Float(), nullable=True),
    sa.Column('venue_lng', sa.Float(), nullable=True),
    sa.Column('max_attendees', sa.Integer(), nullable=True),
    sa.Column('waitlist_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_waitlist', sa.Integer(), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_tenant_id'), 'events', ['tenant_id'], unique=False)
    op.create_table('kpi_snapshots',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Integer(), nullable=False),
    sa.Column('metric_unit', sa.String(length=20), nullable=True),
    sa.Column('dimensions', sa.JSON(), nullable=True),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpi_snapshots_metric_name'), 'kpi_snapshots', ['metric_name'], unique=False)
    op.create_index(op.f('ix_kpi_snapshots_snapshot_date'), 'kpi_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_kpi_snapshots_tenant_id'), 'kpi_snapshots', ['tenant_id'], unique=False)
    op.create_table('saved_reports',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('report_type', sa.Enum('MEMBER', 'FINANCIAL', 'EVENT', 'COMMUNICATION', 'ENGAGEMENT', 'CUSTOM', name='reporttype'), nullable=False),
    sa.Column('query_config', sa.JSON(), nullable=False),
    sa.Column('is_scheduled', sa.Boolean(), nullable=False),
    sa.Column('schedule_cron', sa.String(length=50), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_result', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_reports_tenant_id'), 'saved_reports', ['tenant_id'], unique=False)
    op.create_table('surveys',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('target_segments', sa.JSON(), nullable=True),
    sa.Column('target_all', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'CLOSED', name='surveystatus'), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_invited', sa.Integer(), nullable=False),
    sa.Column('response_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surveys_tenant_id'), 'surveys', ['tenant_id'], unique=False)
    op.create_table('workflow_action_templates',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('action_type', sa.Enum('SEND_EMAIL', 'SEND_NOTIFICATION', 'SEND_SMS', 'UPDATE_MEMBER', 'CREATE_TASK', 'ADD_TO_GROUP', 'REMOVE_FROM_GROUP', 'CREATE_INVOICE', 'GENERATE_REPORT', 'WAIT', 'CONDITION', 'WEBHOOK_CALL', 'AI_ACTION', name='actiontype'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_action_templates_tenant_id'), 'workflow_action_templates', ['tenant_id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'ARCHIVED', name='workflowstatus'), nullable=False),
    sa.Column('trigger_type', sa.Enum('MEMBER_JOIN', 'MEMBER_RENEWAL', 'MEMBER_EXPIRY', 'PAYMENT_RECEIVED', 'PAYMENT_OVERDUE', 'EVENT_REGISTRATION', 'EVENT_REMINDER', 'FORM_SUBMISSION', 'DOCUMENT_UPLOAD', 'MANUAL', 'SCHEDULED', 'WEBHOOK', name='triggertype'), nullable=False),
    sa.Column('trigger_config', sa.JSON(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('total_runs', sa.Integer(), nullable=False),
    sa.Column('successful_runs', sa.Integer(), nullable=False),
    sa.Column('failed_runs', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_tenant_id'), 'workflows', ['tenant_id'], unique=False)
    op.create_table('dashboard_widgets',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('dashboard_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('widget_type', sa.Enum('LINE_CHART', 'BAR_CHART', 'PIE_CHART', 'STAT_CARD', 'TABLE', 'HEATMAP', 'FUNNEL', 'GAUGE', name='dashboardwidgettype'), nullable=False),
    sa.Column('data_source', sa.String(length=100), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('position', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_widgets_dashboard_id'), 'dashboard_widgets', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_dashboard_widgets_tenant_id'), 'dashboard_widgets', ['tenant_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_type', sa.Enum('FILE', 'FOLDER', 'LINK', name='documenttype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', 'DELETED', name='documentstatus'), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('current_version_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('category_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('parent_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('access_level', sa.Enum('PUBLIC', 'MEMBERS', 'STAFF', 'ADMIN', 'RESTRICTED', name='accesslevel'), nullable=False),
    sa.Column('allowed_user_ids', sa.JSON(), nullable=True),
    sa.Column('allowed_group_ids', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['document_categories.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_category_id'), 'documents', ['category_id'], unique=False)
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_table('election_positions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('election_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_election_positions_election_id'), 'election_positions', ['election_id'], unique=False)
    op.create_index(op.f('ix_election_positions_tenant_id'), 'election_positions', ['tenant_id'], unique=False)
    op.create_table('event_sessions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('session_type', sa.Enum('KEYNOTE', 'WORKSHOP', 'PANEL', 'NETWORKING', 'BREAK', 'CUSTOM', name='sessiontype'), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('room', sa.String(length=100), nullable=True),
    sa.Column('track', sa.String(length=100), nullable=True),
    sa.Column('max_attendees', sa.Integer(), nullable=True),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('slides_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_sessions_event_id'), 'event_sessions', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_sessions_tenant_id'), 'event_sessions', ['tenant_id'], unique=False)
    op.create_table('event_sponsors',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_sponsors_event_id'), 'event_sponsors', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_sponsors_tenant_id'), 'event_sponsors', ['tenant_id'], unique=False)
    op.create_table('event_tickets',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ticket_type', sa.Enum('EARLY_BIRD', 'REGULAR', 'VIP', 'STUDENT', 'MEMBER', 'NON_MEMBER', 'FREE', name='tickettype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('max_per_order', sa.Integer(), nullable=False),
    sa.Column('sale_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sale_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_tickets_event_id'), 'event_tickets', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_tickets_tenant_id'), 'event_tickets', ['tenant_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('submitted_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('approved_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('category', sa.Enum('OPERATIONS', 'EVENTS', 'MARKETING', 'TRAVEL', 'TECHNOLOGY', 'PROFESSIONAL_SERVICES', 'FACILITIES', 'INSURANCE', 'OTHER', name='expensecategory'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'REIMBURSED', name='expensestatus'), nullable=False),
    sa.Column('expense_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reimbursed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('receipt_filename', sa.String(length=255), nullable=True),
    sa.Column('budget_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('cost_center', sa.String(length=100), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_tenant_id'), 'expenses', ['tenant_id'], unique=False)
    op.create_table('message_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'PUSH', 'IN_APP', name='channeltype'), nullable=False),
    sa.Column('recipient_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('recipient_email', sa.String(length=200), nullable=True),
    sa.Column('recipient_phone', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body_preview', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('campaign_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clicked_link', sa.String(length=500), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['email_campaigns.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_logs_tenant_id'), 'message_logs', ['tenant_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('survey_responses',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('survey_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('respondent_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['respondent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_responses_survey_id'), 'survey_responses', ['survey_id'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workflow_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'WAITING', 'CANCELLED', name='runstatus'), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('trigger_data', sa.JSON(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('step_results', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_step', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_runs_tenant_id'), 'workflow_runs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_workflow_id'), 'workflow_runs', ['workflow_id'], unique=False)
    op.create_table('ballots',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('election_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('voter_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('votes', sa.JSON(), nullable=False),
    sa.Column('abstentions', sa.JSON(), nullable=True),
    sa.Column('verification_code', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('cast_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['member_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ballots_election_id'), 'ballots', ['election_id'], unique=False)
    op.create_index(op.f('ix_ballots_tenant_id'), 'ballots', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ballots_voter_id'), 'ballots', ['voter_id'], unique=False)
    op.create_table('document_activities',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('document_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('member_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_activities_document_id'), 'document_activities', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_activities_tenant_id'), 'document_activities', ['tenant_id'], unique=False)
    op.create_table('document_comments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('document_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('member_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member_profiles.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['document_comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_comments_document_id'), 'document_comments', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_comments_tenant_id'), 'document_comments', ['tenant_id'], unique=False)
    op.create_table('document_shares',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('document_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('shared_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('shared_with', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['shared_by'], ['member_profiles.id'], ),
    sa.ForeignKeyConstraint(['shared_with'], ['member_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_shares_document_id'), 'document_shares', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_shares_tenant_id'), 'document_shares', ['tenant_id'], unique=False)
    op.create_table('document_versions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('document_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_versions_tenant_id'), 'document_versions', ['tenant_id'], unique=False)
    op.create_table('election_results',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('election_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('position_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('total_votes', sa.Integer(), nullable=False),
    sa.Column('results_detail', sa.JSON(), nullable=False),
    sa.Column('winners', sa.JSON(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['election_positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_election_results_election_id'), 'election_results', ['election_id'], unique=False)
    op.create_index(op.f('ix_election_results_tenant_id'), 'election_results', ['tenant_id'], unique=False)
    op.create_table('event_feedback',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('member_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('session_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('would_recommend', sa.Boolean(), nullable=True),
    sa.Column('improvements', sa.Text(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member_profiles.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['event_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_feedback_event_id'), 'event_feedback', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_feedback_tenant_id'), 'event_feedback', ['tenant_id'], unique=False)
    op.create_table('event_registrations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('member_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('ticket_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'WAITLISTED', 'CHECKED_IN', name='registrationstatus'), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('stripe_payment_id', sa.String(length=100), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_in_method', sa.String(length=50), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dietary_restrictions', sa.String(length=200), nullable=True),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('emergency_contact', sa.String(length=200), nullable=True),
    sa.Column('emergency_phone', sa.String(length=50), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member_profiles.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['event_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_registrations_event_id'), 'event_registrations', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_registrations_member_id'), 'event_registrations', ['member_id'], unique=False)
    op.create_index(op.f('ix_event_registrations_tenant_id'), 'event_registrations', ['tenant_id'], unique=False)
    op.create_table('event_speakers',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('session_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('member_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('linkedin', sa.String(length=500), nullable=True),
    sa.Column('twitter', sa.String(length=200), nullable=True),
    sa.Column('is_keynote', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member_profiles.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['event_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_speakers_event_id'), 'event_speakers', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_speakers_tenant_id'), 'event_speakers', ['tenant_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('member_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('dues_structure_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'PAID', 'OVERDUE', 'CANCELLED', 'REFUNDED', name='invoicestatus'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('line_items', sa.JSON(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('stripe_invoice_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dues_structure_id'], ['dues_structures.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_invoices_member_id'), 'invoices', ['member_id'], unique=False)
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    op.create_table('nominations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('election_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('position_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('member_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'WITHDRAWN', name='nominationstatus'), nullable=False),
    sa.Column('statement', sa.Text(), nullable=True),
    sa.Column('qualifications', sa.Text(), nullable=True),
    sa.Column('endorsed_by', sa.JSON(), nullable=True),
    sa.Column('nominated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member_profiles.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['election_positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nominations_election_id'), 'nominations', ['election_id'], unique=False)
    op.create_index(op.f('ix_nominations_member_id'), 'nominations', ['member_id'], unique=False)
    op.create_index(op.f('ix_nominations_tenant_id'), 'nominations', ['tenant_id'], unique=False)
    op.create_table('recurring_transactions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('member_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('dues_structure_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('next_invoice_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_invoice_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dues_structure_id'], ['dues_structures.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_transactions_tenant_id'), 'recurring_transactions', ['tenant_id'], unique=False)
    op.create_table('workflow_delays',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workflow_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('run_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('resume_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_resumed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_delays_run_id'), 'workflow_delays', ['run_id'], unique=False)
    op.create_index(op.f('ix_workflow_delays_tenant_id'), 'workflow_delays', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_workflow_delays_workflow_id'), 'workflow_delays', ['workflow_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('invoice_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('member_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.Enum('STRIPE', 'BANK_TRANSFER', 'CHECK', 'CASH', 'OTHER', name='paymentmethod'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stripe_charge_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_receipt_url', sa.String(length=500), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_workflow_delays_workflow_id'), table_name='workflow_delays')
    op.drop_index(op.f('ix_workflow_delays_tenant_id'), table_name='workflow_delays')
    op.drop_index(op.f('ix_workflow_delays_run_id'), table_name='workflow_delays')
    op.drop_table('workflow_delays')
    op.drop_index(op.f('ix_recurring_transactions_tenant_id'), table_name='recurring_transactions')
    op.drop_table('recurring_transactions')
    op.drop_index(op.f('ix_nominations_tenant_id'), table_name='nominations')
    op.drop_index(op.f('ix_nominations_member_id'), table_name='nominations')
    op.drop_index(op.f('ix_nominations_election_id'), table_name='nominations')
    op.drop_table('nominations')
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_member_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_event_speakers_tenant_id'), table_name='event_speakers')
    op.drop_index(op.f('ix_event_speakers_event_id'), table_name='event_speakers')
    op.drop_table('event_speakers')
    op.drop_index(op.f('ix_event_registrations_tenant_id'), table_name='event_registrations')
    op.drop_index(op.f('ix_event_registrations_member_id'), table_name='event_registrations')
    op.drop_index(op.f('ix_event_registrations_event_id'), table_name='event_registrations')
    op.drop_table('event_registrations')
    op.drop_index(op.f('ix_event_feedback_tenant_id'), table_name='event_feedback')
    op.drop_index(op.f('ix_event_feedback_event_id'), table_name='event_feedback')
    op.drop_table('event_feedback')
    op.drop_index(op.f('ix_election_results_tenant_id'), table_name='election_results')
    op.drop_index(op.f('ix_election_results_election_id'), table_name='election_results')
    op.drop_table('election_results')
    op.drop_index(op.f('ix_document_versions_tenant_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_document_shares_tenant_id'), table_name='document_shares')
    op.drop_index(op.f('ix_document_shares_document_id'), table_name='document_shares')
    op.drop_table('document_shares')
    op.drop_index(op.f('ix_document_comments_tenant_id'), table_name='document_comments')
    op.drop_index(op.f('ix_document_comments_document_id'), table_name='document_comments')
    op.drop_table('document_comments')
    op.drop_index(op.f('ix_document_activities_tenant_id'), table_name='document_activities')
    op.drop_index(op.f('ix_document_activities_document_id'), table_name='document_activities')
    op.drop_table('document_activities')
    op.drop_index(op.f('ix_ballots_voter_id'), table_name='ballots')
    op.drop_index(op.f('ix_ballots_tenant_id'), table_name='ballots')
    op.drop_index(op.f('ix_ballots_election_id'), table_name='ballots')
    op.drop_table('ballots')
    op.drop_index(op.f('ix_workflow_runs_workflow_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_tenant_id'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_survey_responses_survey_id'), table_name='survey_responses')
    op.drop_table('survey_responses')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_message_logs_tenant_id'), table_name='message_logs')
    op.drop_table('message_logs')
    op.drop_index(op.f('ix_expenses_tenant_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_event_tickets_tenant_id'), table_name='event_tickets')
    op.drop_index(op.f('ix_event_tickets_event_id'), table_name='event_tickets')
    op.drop_table('event_tickets')
    op.drop_index(op.f('ix_event_sponsors_tenant_id'), table_name='event_sponsors')
    op.drop_index(op.f('ix_event_sponsors_event_id'), table_name='event_sponsors')
    op.drop_table('event_sponsors')
    op.drop_index(op.f('ix_event_sessions_tenant_id'), table_name='event_sessions')
    op.drop_index(op.f('ix_event_sessions_event_id'), table_name='event_sessions')
    op.drop_table('event_sessions')
    op.drop_index(op.f('ix_election_positions_tenant_id'), table_name='election_positions')
    op.drop_index(op.f('ix_election_positions_election_id'), table_name='election_positions')
    op.drop_table('election_positions')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_category_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_dashboard_widgets_tenant_id'), table_name='dashboard_widgets')
    op.drop_index(op.f('ix_dashboard_widgets_dashboard_id'), table_name='dashboard_widgets')
    op.drop_table('dashboard_widgets')
    op.drop_index(op.f('ix_workflows_tenant_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_workflow_action_templates_tenant_id'), table_name='workflow_action_templates')
    op.drop_table('workflow_action_templates')
    op.drop_index(op.f('ix_surveys_tenant_id'), table_name='surveys')
    op.drop_table('surveys')
    op.drop_index(op.f('ix_saved_reports_tenant_id'), table_name='saved_reports')
    op.drop_table('saved_reports')
    op.drop_index(op.f('ix_kpi_snapshots_tenant_id'), table_name='kpi_snapshots')
    op.drop_index(op.f('ix_kpi_snapshots_snapshot_date'), table_name='kpi_snapshots')
    op.drop_index(op.f('ix_kpi_snapshots_metric_name'), table_name='kpi_snapshots')
    op.drop_table('kpi_snapshots')
    op.drop_index(op.f('ix_events_tenant_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_email_templates_tenant_id'), table_name='email_templates')
    op.drop_table('email_templates')
    op.drop_index(op.f('ix_email_campaigns_tenant_id'), table_name='email_campaigns')
    op.drop_table('email_campaigns')
    op.drop_index(op.f('ix_elections_tenant_id'), table_name='elections')
    op.drop_table('elections')
    op.drop_index(op.f('ix_dues_structures_tenant_id'), table_name='dues_structures')
    op.drop_table('dues_structures')
    op.drop_index(op.f('ix_document_categories_tenant_id'), table_name='document_categories')
    op.drop_table('document_categories')
    op.drop_index(op.f('ix_data_exports_tenant_id'), table_name='data_exports')
    op.drop_table('data_exports')
    op.drop_index(op.f('ix_dashboards_tenant_id'), table_name='dashboards')
    op.drop_table('dashboards')
    op.drop_index(op.f('ix_budgets_tenant_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_announcements_tenant_id'), table_name='announcements')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_ai_insights_tenant_id'), table_name='ai_insights')
    op.drop_table('ai_insights')
    # ### end Alembic commands ###
