"""add ai and integrations modules

Revision ID: 733cc2117d46
Revises: 0040638c77bf
Create Date: 2026-07-22 17:57:50.064961
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '733cc2117d46'
down_revision: Union[str, None] = '0040638c77bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_conversations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='conversationrole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_session_id'), 'ai_conversations', ['session_id'], unique=False)
    op.create_index(op.f('ix_ai_conversations_tenant_id'), 'ai_conversations', ['tenant_id'], unique=False)
    op.create_table('ai_embeddings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('content_id', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.Enum('MEMBER', 'DOCUMENT', 'EVENT', 'TRANSACTION', 'COMMUNICATION', 'POLICY', 'CUSTOM', name='contenttype'), nullable=False),
    sa.Column('text_chunk', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_embeddings_content_id'), 'ai_embeddings', ['content_id'], unique=False)
    op.create_index(op.f('ix_ai_embeddings_content_type'), 'ai_embeddings', ['content_type'], unique=False)
    op.create_index(op.f('ix_ai_embeddings_tenant_id'), 'ai_embeddings', ['tenant_id'], unique=False)
    op.create_table('ai_models',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('model_type', sa.Enum('CHURN_PREDICTION', 'ANOMALY_DETECTION', 'RECOMMENDATION', 'CLASSIFICATION', 'REGRESSION', 'CUSTOM', name='modeltype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_models_tenant_id'), 'ai_models', ['tenant_id'], unique=False)
    op.create_table('ai_predictions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('prediction_type', sa.Enum('CHURN_RISK', 'ANOMALY', 'RECOMMENDATION', 'CLASSIFICATION', 'SCORING', name='predictiontype'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_predictions_entity_id'), 'ai_predictions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_ai_predictions_entity_type'), 'ai_predictions', ['entity_type'], unique=False)
    op.create_index(op.f('ix_ai_predictions_model_id'), 'ai_predictions', ['model_id'], unique=False)
    op.create_index(op.f('ix_ai_predictions_tenant_id'), 'ai_predictions', ['tenant_id'], unique=False)
    op.create_table('integration_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('source_module', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_events_tenant_id'), 'integration_events', ['tenant_id'], unique=False)
    op.create_table('integrations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('integration_type', sa.Enum('STRIPE', 'SLACK', 'GOOGLE_CALENDAR', 'ZAPIER', 'CUSTOM', name='integrationtype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ERROR', 'PENDING', name='integrationstatus'), nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrations_tenant_id'), 'integrations', ['tenant_id'], unique=False)
    op.create_table('webhooks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('events', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('secret', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhooks_tenant_id'), 'webhooks', ['tenant_id'], unique=False)
    op.create_table('webhook_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('webhook_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_logs_tenant_id'), 'webhook_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_webhook_id'), 'webhook_logs', ['webhook_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_logs_webhook_id'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_tenant_id'), table_name='webhook_logs')
    op.drop_table('webhook_logs')
    op.drop_index(op.f('ix_webhooks_tenant_id'), table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_integrations_tenant_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_integration_events_tenant_id'), table_name='integration_events')
    op.drop_table('integration_events')
    op.drop_index(op.f('ix_ai_predictions_tenant_id'), table_name='ai_predictions')
    op.drop_index(op.f('ix_ai_predictions_model_id'), table_name='ai_predictions')
    op.drop_index(op.f('ix_ai_predictions_entity_type'), table_name='ai_predictions')
    op.drop_index(op.f('ix_ai_predictions_entity_id'), table_name='ai_predictions')
    op.drop_table('ai_predictions')
    op.drop_index(op.f('ix_ai_models_tenant_id'), table_name='ai_models')
    op.drop_table('ai_models')
    op.drop_index(op.f('ix_ai_embeddings_tenant_id'), table_name='ai_embeddings')
    op.drop_index(op.f('ix_ai_embeddings_content_type'), table_name='ai_embeddings')
    op.drop_index(op.f('ix_ai_embeddings_content_id'), table_name='ai_embeddings')
    op.drop_table('ai_embeddings')
    op.drop_index(op.f('ix_ai_conversations_tenant_id'), table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_session_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    # ### end Alembic commands ###
