"""Initial schema - all 9 modules

Revision ID: ac8b8a4a13f3
Revises: 
Create Date: 2026-07-22 14:10:17.722258
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac8b8a4a13f3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_groups',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('group_type', sa.Enum('CHAPTER', 'COMMITTEE', 'INTEREST_GROUP', 'WORKING_GROUP', 'BOARD', name='grouptype'), nullable=False),
    sa.Column('parent_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('meeting_schedule', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['member_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_groups_tenant_id'), 'member_groups', ['tenant_id'], unique=False)
    op.create_table('member_tags',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_tags_tenant_id'), 'member_tags', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('member_activity_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_activity_logs_tenant_id'), 'member_activity_logs', ['tenant_id'], unique=False)
    op.create_table('member_profiles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('member_number', sa.String(length=50), nullable=True),
    sa.Column('tier', sa.Enum('FREE', 'BASIC', 'PREMIUM', 'CORPORATE', 'LIFETIME', name='membershiptier'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'LAPSED', 'CANCELLED', name='memberstatus'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('renewal_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('address', sa.JSON(), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=True),
    sa.Column('email_opt_in', sa.Boolean(), nullable=False),
    sa.Column('sms_opt_in', sa.Boolean(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('churn_risk', sa.Float(), nullable=False),
    sa.Column('lifetime_value', sa.Float(), nullable=False),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_member_profiles_tenant_id'), 'member_profiles', ['tenant_id'], unique=False)
    op.create_table('member_group_memberships',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('member_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('group_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.Enum('MEMBER', 'CHAIR', 'CO_CHAIR', 'SECRETARY', 'TREASURER', name='groupmemberrole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['member_groups.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_notes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('member_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('author_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_notes_tenant_id'), 'member_notes', ['tenant_id'], unique=False)
    op.create_table('member_profile_tags',
    sa.Column('member_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tag_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member_profiles.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['member_tags.id'], ),
    sa.PrimaryKeyConstraint('member_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_profile_tags')
    op.drop_index(op.f('ix_member_notes_tenant_id'), table_name='member_notes')
    op.drop_table('member_notes')
    op.drop_table('member_group_memberships')
    op.drop_index(op.f('ix_member_profiles_tenant_id'), table_name='member_profiles')
    op.drop_table('member_profiles')
    op.drop_index(op.f('ix_member_activity_logs_tenant_id'), table_name='member_activity_logs')
    op.drop_table('member_activity_logs')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_member_tags_tenant_id'), table_name='member_tags')
    op.drop_table('member_tags')
    op.drop_index(op.f('ix_member_groups_tenant_id'), table_name='member_groups')
    op.drop_table('member_groups')
    # ### end Alembic commands ###
